#include "constructStringFromBinaryTree/constructStringFromBinaryTree.hpp"
#include "cutOffTreesForGolfEvent/cutOffTreesForGolfEvent.hpp"
#include "maximumLengthOfPairChain/maximumLengthOfPairChain.hpp"
#include "searchSuggestionsSystem.hpp"
#include "subtreeOfAnotherTree/subtreeOfAnotherTree.hpp"